name: Backup Firestore

on:
  schedule:
    - cron:  '0 0 * * *'

env:
  PROJECT_ID: homeslack-12280
  BUCKET: gs://homeslack-12280.appspot.com/backups
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info
    - run: gcloud config set project $homeslack-12280
    - run: gcloud firestore export $gs://homeslack-12280.appspot.com/backups
